name: Tests (PHP)
on: [push, pull_request]

jobs:
    tests:
        name: Run PhpUnit tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                php: [7.2, 7.3, 7.4]
                os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
                composer_flags: ['--prefer-lowest', '']
        steps:
            - uses: actions/checkout@v1

            - name: Configure PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring
                  coverage: none

            - name: Install Composer dependencies
              run: composer update --no-interaction --no-suggest --no-progress --prefer-dist ${{ matrix.composer_flags }}

            - name: Execute tests
              run: vendor/bin/phpunit
